image: jsfn/golang-protoc

before_script:
    - "git submodule init"
    - "go get -v -u github.com/golang/protobuf/{proto,protoc-gen-go}"
    - "go get -v -u github.com/mitchellh/gox"
    - "go get -v -u github.com/tcnksm/ghr"
    - "go get -v -u google.golang.org/grpc"
    - "go get -v -u gitlab.com/piLights/proto"
    - "./buildscript.sh"

after_script:
    - curl -Iv --user "${USERNAME}:${PASSWORD}" -T ul https://binupload.pilights.jf-projects.de

.compileAndUploadTemplate: &compileAndUpload
    script:
        - "/bin/bash ./scripts/build.sh"
    artifacts:
        paths:
            - dist/

Linux:
    <<: *compileAndUpload
    variables:
        OPERATING_SYSTEM: "linux"


Windows:
    <<: *compileAndUpload
    variables:
        OPERATING_SYSTEM: "windows"

OpenBSD:
    <<: *compileAndUpload
    variables:
        OPERATING_SYSTEM: "openbsd"

FreeBSD:
    <<: *compileAndUpload
    variables:
        OPERATING_SYSTEM: "freebsd"

NetBSD:
    <<: *compileAndUpload
    variables:
        OPERATING_SYSTEM: "netbsd"

Darwin:
    <<: *compileAndUpload
    variables:
        OPERATING_SYSTEM: "darwin"
