image: registry.gitlab.com/jannickfahlbusch/docker-proto:latest

before_script:
    - "git submodule init"
    - "go get -v -u github.com/golang/protobuf/{proto,protoc-gen-go}"
    - "go get -v -u github.com/mitchellh/gox"
    - "go get -v -u github.com/tcnksm/ghr"
    - "go get -v -u google.golang.org/grpc"
    - "go get -v -u gitlab.com/piLights/proto"
    - "./buildscript.sh"

after_script:
    - "/bin/bash ./scripts/generateHashsums.sh"

.compileAndUploadTemplate: &compileAndUpload
    script:
        - "/bin/bash ./scripts/build.sh"
    artifacts:
        paths:
            - dist/

Build:
    <<: *compileAndUpload
    variables:
        OPERATING_SYSTEM: "linux"
