image: jsfn/golang-protoc

before_script:
    - "go get -v -u github.com/golang/protobuf/{proto,protoc-gen-go}"
    - "go get -v -u github.com/mitchellh/gox"
    - "go get -v -u github.com/tcnksm/ghr"
    - "go get -v -u google.golang.org/grpc"
    - "./buildscript.sh"

Linux:
    script:
        - "/bin/bash ./scripts/build.sh"
    variables:
        OPERATING_SYSTEM: "linux"
    artifacts:
        paths:
            - dist/

Windows:
    script:
        - "/bin/bash ./scripts/build.sh"
    variables:
        OPERATING_SYSTEM: "windows"
    artifacts:
        paths:
            - dist/

OpenBSD:
    script:
        - "/bin/bash ./scripts/build.sh"
    variables:
        OPERATING_SYSTEM: "openbsd"
    artifacts:
        paths:
            - dist/

FreeBSD:
    script:
        - "/bin/bash ./scripts/build.sh"
    variables:
        OPERATING_SYSTEM: "freebsd"
    artifacts:
        paths:
            - dist/

NetBSD:
    script:
        - "/bin/bash ./scripts/build.sh"
    variables:
        OPERATING_SYSTEM: "netbsd"
    artifacts:
        paths:
            - dist/

Darwin:
    script:
        - "/bin/bash ./scripts/build.sh"
    variables:
        OPERATING_SYSTEM: "darwin"
    artifacts:
        paths:
            - dist/
