image: registry.gitlab.com/jannickfahlbusch/docker-proto:latest

variables:
  S3_BUCKET_NAME: "dl.pilights.jf-projects.de"

before_script:
    - "git submodule init"
    - "go get -v -u github.com/golang/protobuf/{proto,protoc-gen-go}"
    - "go get -v -u github.com/mitchellh/gox"
    - "go get -v -u github.com/tcnksm/ghr"
    - "go get -v -u google.golang.org/grpc"
    - "go get -v -u gitlab.com/piLights/proto"
    - "./buildscript.sh"

after_script:
    - aws s3 cp ./dist/* s3://$S3_BUCKET_NAME/

.compileAndUploadTemplate: &compileAndUpload
    script:
        - "/bin/bash ./scripts/build.sh"
    artifacts:
        paths:
            - dist/

Linux:
    <<: *compileAndUpload
    variables:
        OPERATING_SYSTEM: "linux"


Windows:
    <<: *compileAndUpload
    variables:
        OPERATING_SYSTEM: "windows"

OpenBSD:
    <<: *compileAndUpload
    variables:
        OPERATING_SYSTEM: "openbsd"

FreeBSD:
    <<: *compileAndUpload
    variables:
        OPERATING_SYSTEM: "freebsd"

NetBSD:
    <<: *compileAndUpload
    variables:
        OPERATING_SYSTEM: "netbsd"

Darwin:
    <<: *compileAndUpload
    variables:
        OPERATING_SYSTEM: "darwin"
