language: go
sudo: true

env:
    - OPERATING_SYSTEM=linux
    - OPERATING_SYSTEM=windows
    - OPERATING_SYSTEM=openbsd
    - OPERATING_SYSTEM=freebsd
    - OPERATING_SYSTEM=netbsd
    - OPERATING_SYSTEM=darwin

go:
  - 1.6

before_install:
  - ./scripts/installProtobuf.sh
  - go get -u github.com/golang/protobuf/{proto,protoc-gen-go}
  - go get -u github.com/mitchellh/gox
  - go get -u github.com/tcnksm/ghr
  - go get -u google.golang.org/grpc
  - cd $HOME/gopath/src/github.com/piLights/dioder-rpc

install:
    - cd src/; go get; cd ..

script:
  - ./buildscript.sh

after_success:
    - cd src/; gox -output "../dist/dioderAPI_{{.OS}}_{{.Arch}}" -parallel=2 -verbose -os="${OPERATING_SYSTEM}"; cd ..
    - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && ghr --username piLights --token $GITHUB_TOKEN --replace --prerelease --debug pre-release dist/'
