language: go
sudo: true

go:
  - 1.6
  - tip

before_install:
  - ./scripts/installProtobuf.sh
  - go get github.com/golang/protobuf/{proto,protoc-gen-go}
  - go get github.com/mitchellh/gox
  - go get github.com/tcnksm/ghr

install:
    - cd src/; go get; cd ..

script:
  - ./buildscript.sh
