language: go
sudo: true

go:
  - 1.6
  - tip

before_install:
  - ./scripts/installProtobuf.sh
  - go get github.com/golang/protobuf/{proto,protoc-gen-go}
  - go get github.com/mitchellh/gox
  - go get github.com/tcnksm/ghr
  - cd $GOPATH/src/google.golang.org/grpc; git checkout dec33edc378cf4971a2741cfd86ed70a644d6ba3

install:
    - cd src/; go get; cd ..

script:
  - ./buildscript.sh

after_success:
    - cd src/; gox -output "../dist/{{.OS}}_{{.Arch}}_{{.Dir}}" -verbose
