language: go
sudo: true

env:
    - OPERATING_SYSTEM=linux
    - OPERATING_SYSTEM=windows
    - OPERATING_SYSTEM=openbsd
    - OPERATING_SYSTEM=freebsd
    - OPERATING_SYSTEM=netbsd
    - OPERATING_SYSTEM=darwin

go:
  - 1.6

before_install:
  - ./scripts/installProtobuf.sh
  - go get -v -u github.com/golang/protobuf/{proto,protoc-gen-go}
  - go get -v -u github.com/mitchellh/gox
  - go get -v -u github.com/tcnksm/ghr
  - go get -v -u google.golang.org/grpc
  - cd $HOME/gopath/src/github.com/piLights/dioder-rpc

install:
    - cd src/; go get; cd ..

script:
  - ./buildscript.sh

after_success:
    - ./scripts/deploy.sh
