// Code generated by protoc-gen-go.
// source: lighter.proto
// DO NOT EDIT!

/*
Package LighterGRPC is a generated protocol buffer package.

It is generated from these files:
	lighter.proto

It has these top-level messages:
	ColorMessage
	StateMessage
	Confirmation
	InitMessage
*/
package LighterGRPC

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type ColorMessage struct {
	Onstate  bool   `protobuf:"varint,1,opt,name=onstate" json:"onstate,omitempty"`
	R        int32  `protobuf:"varint,2,opt,name=r" json:"r,omitempty"`
	G        int32  `protobuf:"varint,3,opt,name=g" json:"g,omitempty"`
	B        int32  `protobuf:"varint,4,opt,name=b" json:"b,omitempty"`
	Opacity  int32  `protobuf:"varint,5,opt,name=opacity" json:"opacity,omitempty"`
	DeviceID string `protobuf:"bytes,6,opt,name=deviceID" json:"deviceID,omitempty"`
	Password string `protobuf:"bytes,7,opt,name=password" json:"password,omitempty"`
}

func (m *ColorMessage) Reset()                    { *m = ColorMessage{} }
func (m *ColorMessage) String() string            { return proto.CompactTextString(m) }
func (*ColorMessage) ProtoMessage()               {}
func (*ColorMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type StateMessage struct {
	Onstate  bool   `protobuf:"varint,1,opt,name=onstate" json:"onstate,omitempty"`
	DeviceID string `protobuf:"bytes,2,opt,name=deviceID" json:"deviceID,omitempty"`
	Password string `protobuf:"bytes,3,opt,name=password" json:"password,omitempty"`
}

func (m *StateMessage) Reset()                    { *m = StateMessage{} }
func (m *StateMessage) String() string            { return proto.CompactTextString(m) }
func (*StateMessage) ProtoMessage()               {}
func (*StateMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type Confirmation struct {
	Success bool `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
}

func (m *Confirmation) Reset()                    { *m = Confirmation{} }
func (m *Confirmation) String() string            { return proto.CompactTextString(m) }
func (*Confirmation) ProtoMessage()               {}
func (*Confirmation) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type InitMessage struct {
	DeviceID string `protobuf:"bytes,1,opt,name=deviceID" json:"deviceID,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
}

func (m *InitMessage) Reset()                    { *m = InitMessage{} }
func (m *InitMessage) String() string            { return proto.CompactTextString(m) }
func (*InitMessage) ProtoMessage()               {}
func (*InitMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func init() {
	proto.RegisterType((*ColorMessage)(nil), "LighterGRPC.ColorMessage")
	proto.RegisterType((*StateMessage)(nil), "LighterGRPC.StateMessage")
	proto.RegisterType((*Confirmation)(nil), "LighterGRPC.Confirmation")
	proto.RegisterType((*InitMessage)(nil), "LighterGRPC.InitMessage")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion2

// Client API for Lighter service

type LighterClient interface {
	SetColor(ctx context.Context, in *ColorMessage, opts ...grpc.CallOption) (*Confirmation, error)
	CheckConnection(ctx context.Context, in *InitMessage, opts ...grpc.CallOption) (Lighter_CheckConnectionClient, error)
	SwitchState(ctx context.Context, in *StateMessage, opts ...grpc.CallOption) (*Confirmation, error)
}

type lighterClient struct {
	cc *grpc.ClientConn
}

func NewLighterClient(cc *grpc.ClientConn) LighterClient {
	return &lighterClient{cc}
}

func (c *lighterClient) SetColor(ctx context.Context, in *ColorMessage, opts ...grpc.CallOption) (*Confirmation, error) {
	out := new(Confirmation)
	err := grpc.Invoke(ctx, "/LighterGRPC.Lighter/setColor", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lighterClient) CheckConnection(ctx context.Context, in *InitMessage, opts ...grpc.CallOption) (Lighter_CheckConnectionClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Lighter_serviceDesc.Streams[0], c.cc, "/LighterGRPC.Lighter/checkConnection", opts...)
	if err != nil {
		return nil, err
	}
	x := &lighterCheckConnectionClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Lighter_CheckConnectionClient interface {
	Recv() (*ColorMessage, error)
	grpc.ClientStream
}

type lighterCheckConnectionClient struct {
	grpc.ClientStream
}

func (x *lighterCheckConnectionClient) Recv() (*ColorMessage, error) {
	m := new(ColorMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *lighterClient) SwitchState(ctx context.Context, in *StateMessage, opts ...grpc.CallOption) (*Confirmation, error) {
	out := new(Confirmation)
	err := grpc.Invoke(ctx, "/LighterGRPC.Lighter/switchState", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Lighter service

type LighterServer interface {
	SetColor(context.Context, *ColorMessage) (*Confirmation, error)
	CheckConnection(*InitMessage, Lighter_CheckConnectionServer) error
	SwitchState(context.Context, *StateMessage) (*Confirmation, error)
}

func RegisterLighterServer(s *grpc.Server, srv LighterServer) {
	s.RegisterService(&_Lighter_serviceDesc, srv)
}

func _Lighter_SetColor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ColorMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LighterServer).SetColor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/LighterGRPC.Lighter/SetColor",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LighterServer).SetColor(ctx, req.(*ColorMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Lighter_CheckConnection_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(InitMessage)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LighterServer).CheckConnection(m, &lighterCheckConnectionServer{stream})
}

type Lighter_CheckConnectionServer interface {
	Send(*ColorMessage) error
	grpc.ServerStream
}

type lighterCheckConnectionServer struct {
	grpc.ServerStream
}

func (x *lighterCheckConnectionServer) Send(m *ColorMessage) error {
	return x.ServerStream.SendMsg(m)
}

func _Lighter_SwitchState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StateMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LighterServer).SwitchState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/LighterGRPC.Lighter/SwitchState",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LighterServer).SwitchState(ctx, req.(*StateMessage))
	}
	return interceptor(ctx, in, info, handler)
}

var _Lighter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "LighterGRPC.Lighter",
	HandlerType: (*LighterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "setColor",
			Handler:    _Lighter_SetColor_Handler,
		},
		{
			MethodName: "switchState",
			Handler:    _Lighter_SwitchState_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "checkConnection",
			Handler:       _Lighter_CheckConnection_Handler,
			ServerStreams: true,
		},
	},
}

var fileDescriptor0 = []byte{
	// 316 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x84, 0x92, 0xdd, 0x4e, 0x83, 0x30,
	0x18, 0x86, 0x57, 0xe6, 0x06, 0x76, 0x18, 0x93, 0x7a, 0x60, 0xe5, 0xc8, 0x70, 0xb4, 0x23, 0x62,
	0xf4, 0x0e, 0x36, 0x8d, 0x99, 0xd1, 0x64, 0xc1, 0x1b, 0x10, 0x4a, 0x85, 0x66, 0xb3, 0x25, 0x6d,
	0xe7, 0xe2, 0xfd, 0x78, 0x61, 0x5e, 0x8a, 0x94, 0x1f, 0xed, 0x48, 0xc4, 0xc3, 0xe7, 0xfb, 0x08,
	0xcf, 0xdb, 0xbe, 0x85, 0x27, 0x5b, 0x96, 0x17, 0x9a, 0xca, 0xa8, 0x94, 0x42, 0x0b, 0x34, 0x7b,
	0x6c, 0xf0, 0x3e, 0x5e, 0x2f, 0xc3, 0x4f, 0x00, 0xfd, 0xa5, 0xd8, 0x0a, 0xf9, 0x44, 0x95, 0x4a,
	0x72, 0x8a, 0x30, 0x74, 0x05, 0x57, 0x3a, 0xd1, 0x14, 0x83, 0x4b, 0x30, 0xf7, 0xe2, 0x0e, 0x91,
	0x0f, 0x81, 0xc4, 0x4e, 0x35, 0x9b, 0xc4, 0x40, 0x1a, 0xca, 0xf1, 0xb8, 0xa1, 0xdc, 0x50, 0x8a,
	0x8f, 0x1a, 0x4a, 0xeb, 0x7f, 0x94, 0x09, 0x61, 0xfa, 0x03, 0x4f, 0xea, 0x59, 0x87, 0x28, 0x80,
	0x5e, 0x46, 0xdf, 0x19, 0xa1, 0xab, 0x5b, 0x3c, 0xad, 0x56, 0xc7, 0xf1, 0x0f, 0x9b, 0x5d, 0x99,
	0x28, 0xb5, 0x17, 0x32, 0xc3, 0x6e, 0xb3, 0xeb, 0x38, 0x7c, 0x81, 0xfe, 0xb3, 0x09, 0xf1, 0x7f,
	0x4a, 0xdb, 0xe0, 0x0c, 0x18, 0xc6, 0x3d, 0xc3, 0xdc, 0xdc, 0x03, 0x7f, 0x65, 0xf2, 0x2d, 0xd1,
	0x4c, 0x70, 0x63, 0x50, 0x3b, 0x42, 0x2a, 0x5f, 0x67, 0x68, 0x31, 0xbc, 0x83, 0xb3, 0x15, 0x67,
	0xba, 0x8b, 0x62, 0x0b, 0xc1, 0x80, 0xd0, 0x39, 0x14, 0x5e, 0x7f, 0x01, 0xe8, 0xb6, 0x4d, 0xa0,
	0x05, 0xf4, 0x14, 0xd5, 0x75, 0x0f, 0xe8, 0x22, 0xb2, 0xfa, 0x89, 0xec, 0x6e, 0x82, 0xfe, 0xea,
	0x37, 0x6e, 0x38, 0x42, 0x0f, 0xf0, 0x94, 0x14, 0x94, 0x6c, 0xaa, 0x31, 0xa7, 0xa4, 0x39, 0xc3,
	0xc1, 0xf7, 0x56, 0xe8, 0xe0, 0x6f, 0x49, 0x38, 0xba, 0x02, 0xa8, 0x3a, 0xa2, 0xda, 0x33, 0x4d,
	0x8a, 0xfa, 0xd2, 0x7b, 0x91, 0xec, 0x22, 0x06, 0x23, 0x2d, 0xce, 0xe1, 0x59, 0x46, 0xa3, 0x5c,
	0xee, 0x38, 0x23, 0x1b, 0x1a, 0xb5, 0xcf, 0x70, 0x0d, 0xd2, 0x69, 0xfd, 0x12, 0x6f, 0xbe, 0x03,
	0x00, 0x00, 0xff, 0xff, 0x28, 0x6d, 0x10, 0x86, 0x9a, 0x02, 0x00, 0x00,
}
